[package]
edition = "2021"
name = "exchange-service"
version = "0.1.0"

[dependencies]
prost = "0.11"
serde = {version = "1", features = ["derive"]}
tonic = "0.8"

[build-dependencies]
tonic-build = "0.8"
