[package]
edition = "2021"
name = "exchange-domain"
version = "0.1.0"

[dependencies]
bytes = "1.2"
prost = "0.11"
serde = {version = "1", features = ["derive"]}

[build-dependencies]
prost-build = "0.11"
